version: '3'

services:
  nginx:
    build:
      args:
        VERSION: $NGINX_VERSION
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      target: dev
    volumes:
      - ./public:/app/public
      - ./assets/css:/app/public/css
      - ./assets/js:/app/public/js
    depends_on:
      - php-fpm
    ports:
      - 8000:80

  php-fpm:
    build:
      args:
        VERSION: $PHP_VERSION
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
      target: dev
    volumes:
      - ./:/app
    command: sh -c 'XDEBUG_MODE=off composer install --no-interaction --optimize-autoloader && php-fpm'
    depends_on:
      - database
      - redis
      - rabbitmq

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-symfony}
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  redis:
    image: redis:5-alpine
    ports: [6379]
  rabbitmq:
    image: rabbitmq:3.7-management
    ports: [ 5672, 15672 ]
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
