database:
    type: postgresql:13
    disk: 1024
varnish:
    type: varnish:7.0
    relationships:
        application: 'app:http'
    configuration:
        vcl: !include
            type: string
            path: config.vcl